version: '3.8'

services:
  web:
    build:
      context: ./flask-api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: postgresql://postgres:password@db:5432/mydatabase
      MYSQL_HOST: db  # Use service name as MySQL host within Docker network
    depends_on:
      - db
    volumes:
      - ./flask-api:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  postgres_data:
